In [3]:
import pandas as pd

In [5]:
df = pd.read_csv(r'C:\Programming\Python\msba_capstone_dragonsteel\Goodreads Data\Alcatraz_vs_Evil_Librarians.csv')
df

,Author,Title,Published Date,Audience Genre,Description,Average Rating,Total Ratings,Total Reviews,Non-Audience Genres,Currently Reading,Want to Read,URL
0,Brandon Sanderson,Alcatraz Versus the Evil Librarians,"October 1, 2007","Young Adult, Middle Grade, Childrens",Alcatraz Versus the Evil Librariansis the firs...,3.92,35429,5172,"Fantasy, Fiction, Audiobook, Humor",1799,30572,https://www.goodreads.com/book/show/623976.Alc...

In [7]:
df_book = pd.read_csv(r'C:\Programming\Python\msba_capstone_dragonsteel\Alcatraz_Versus_the_Evil_Librarians_reviews_graphql.csv')
df_book

,rating,review_text,created_at,likes,comment_count,review_length,word_count,book_title,book_author,reviewer_name,reviewer_id,review_id,spoiler_status
0,5,For the record: listened to this one on audio....,2015-01-11,266,8,754,132,Alcatraz Versus the Evil Librarians,Brandon Sanderson,Patrick,922495,kca://review:goodreads/amzn1.gr.review:goodrea...,False
1,3,Also known as The Official Author's Notes for ...,2016-09-07,175,39,5460,919,Alcatraz Versus the Evil Librarians,Brandon Sanderson,carol.,3978225,kca://review:goodreads/amzn1.gr.review:goodrea...,False
2,5,5 EYE-OPENING ST★RSHeads up! Goodreads librari...,2016-03-28,122,18,2444,407,Alcatraz Versus the Evil Librarians,Brandon Sanderson,Twila,4585336,kca://review:goodreads/amzn1.gr.review:goodrea...,False
3,2,Zaczynam się zastanawiać czy nie zaniżam ocen ...,2023-03-19,100,1,87,12,Alcatraz Versus the Evil Librarians,Brandon Sanderson,Nikola,91469730,kca://review:goodreads/amzn1.gr.review:goodrea...,False
4,4,Brandon Sanderson can write an instruction man...,2014-12-14,76,16,4219,710,Alcatraz Versus the Evil Librarians,Brandon Sanderson,TS Chan,30279227,kca://review:goodreads/amzn1.gr.review:goodrea...,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,3,I chose to read this book because it was a req...,2021-04-28,0,0,1233,230,Alcatraz Versus the Evil Librarians,Brandon Sanderson,Jecelynn,33844875,kca://review:goodreads/amzn1.gr.review:goodrea...,False
1496,2,Belki de Kralların Yolu gibi muhteşem bir kita...,2021-05-08,0,0,372,54,Alcatraz Versus the Evil Librarians,Brandon Sanderson,Ebubekir,76294612,kca://review:goodreads/amzn1.gr.review:goodrea...,False
1497,3,"I wanted more story and less narration!! But, ...",2021-05-09,0,0,314,54,Alcatraz Versus the Evil Librarians,Brandon Sanderson,Clay Stevenson,2409895,kca://review:goodreads/amzn1.gr.review:goodrea...,True
1498,5,I read this book to my oldest son (8 yrs old g...,2021-05-17,0,0,309,59,Alcatraz Versus the Evil Librarians,Brandon Sanderson,Erik Koster,1553959,kca://review:goodreads/amzn1.gr.review:goodrea...,False
1499,5,"A quirky, funny book. I have just one question...",2021-07-16,0,0,304,50,Alcatraz Versus the Evil Librarians,Brandon Sanderson,Jeff Go,63843067,kca://review:goodreads/amzn1.gr.review:goodrea...,False

In [8]:
def clean_data(df):
    # Drop rows with missing data in column: 'review_text'
    df = df.dropna(subset=['review_text'])
    # Drop rows with missing data in column: 'likes'
    df = df.dropna(subset=['likes'])
    # Drop rows with missing data in column: 'comment_count'
    df = df.dropna(subset=['comment_count'])
    # Drop unnecessary columns (reviewer_name, reviewer_id, review_id)
    df = df.drop(columns=['reviewer_name', 'reviewer_id', 'review_id'])
    return df

# Loaded variable 'df' from URI: c:\Programming\Python\msba_capstone_dragonsteel\Goodreads Data\combined_reviews_graphql.csv
df_clean = clean_data(df_book.copy())
df_clean.head()

,rating,review_text,created_at,likes,comment_count,review_length,word_count,book_title,book_author,spoiler_status
0,5,For the record: listened to this one on audio....,2015-01-11,266,8,754,132,Alcatraz Versus the Evil Librarians,Brandon Sanderson,False
1,3,Also known as The Official Author's Notes for ...,2016-09-07,175,39,5460,919,Alcatraz Versus the Evil Librarians,Brandon Sanderson,False
2,5,5 EYE-OPENING ST★RSHeads up! Goodreads librari...,2016-03-28,122,18,2444,407,Alcatraz Versus the Evil Librarians,Brandon Sanderson,False
3,2,Zaczynam się zastanawiać czy nie zaniżam ocen ...,2023-03-19,100,1,87,12,Alcatraz Versus the Evil Librarians,Brandon Sanderson,False
4,4,Brandon Sanderson can write an instruction man...,2014-12-14,76,16,4219,710,Alcatraz Versus the Evil Librarians,Brandon Sanderson,False

In [9]:
import re

def clean_review(text):
    if not isinstance(text, str):
        return ""
    
    # lowercase
    text = text.lower()
    
    # normalize unicode quotes
    text = re.sub(r"[“”]", '"', text)
    text = re.sub(r"[‘’]", "'", text)
    
    # space out punctuation
    text = re.sub(r"([!?,.()])", r" \1 ", text)
    
    # remove control characters / strange symbols
    # but DO NOT remove emojis or punctuation
    text = re.sub(r"[^\w\s,.!?'\-—–…⭐️🤷‍♀️🤷‍♂️😍😡😢✨]+", " ", text)

    # collapse spaces
    text = re.sub(r"\s+", " ", text).strip()
    
    return text

df_clean["cleaned_review_text"] = df_clean["review_text"].apply(clean_review)

In [10]:
df_clean.head()

,rating,review_text,created_at,likes,comment_count,review_length,word_count,book_title,book_author,spoiler_status,cleaned_review_text
0,5,For the record: listened to this one on audio....,2015-01-11,266,8,754,132,Alcatraz Versus the Evil Librarians,Brandon Sanderson,False,for the record listened to this one on audio ....
1,3,Also known as The Official Author's Notes for ...,2016-09-07,175,39,5460,919,Alcatraz Versus the Evil Librarians,Brandon Sanderson,False,also known as the official author's notes for ...
2,5,5 EYE-OPENING ST★RSHeads up! Goodreads librari...,2016-03-28,122,18,2444,407,Alcatraz Versus the Evil Librarians,Brandon Sanderson,False,5 eye-opening st rsheads up ! goodreads librar...
3,2,Zaczynam się zastanawiać czy nie zaniżam ocen ...,2023-03-19,100,1,87,12,Alcatraz Versus the Evil Librarians,Brandon Sanderson,False,zaczynam się zastanawiać czy nie zaniżam ocen ...
4,4,Brandon Sanderson can write an instruction man...,2014-12-14,76,16,4219,710,Alcatraz Versus the Evil Librarians,Brandon Sanderson,False,brandon sanderson can write an instruction man...

In [11]:
### Sentiment Analysis

# Import necessary libraries
from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline

# Load the multilingual sentiment analysis model and tokenizer
tokenizer = AutoTokenizer.from_pretrained("tabularisai/multilingual-sentiment-analysis")
model = AutoModelForSequenceClassification.from_pretrained("tabularisai/multilingual-sentiment-analysis")

# Create a sentiment analysis pipeline
sentiment_pipeline = pipeline(
    "sentiment-analysis",
    model=model,
    tokenizer=tokenizer,
    truncation=True ## Some reviews may be longer than model's max length
)

# Example usage
sentiment_pipeline("I absolutely loved this book, it was amazing!")

C:\Users\grega\AppData\Roaming\Python\Python313\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Device set to use cpu

[{'label': 'Very Positive', 'score': 0.6916782259941101}]

In [12]:
## Run sentiment analysis on the cleaned reviews
# This will create a new column with the label
df_clean["sentiment_label"] = df_clean["cleaned_review_text"].apply(
    lambda x: sentiment_pipeline(x)[0]["label"]
)

# If you also want the confidence score
df_clean["sentiment_score"] = df_clean["cleaned_review_text"].apply(
    lambda x: sentiment_pipeline(x)[0]["score"]
)

In [13]:
df_clean.head()

,rating,review_text,created_at,likes,comment_count,review_length,word_count,book_title,book_author,spoiler_status,cleaned_review_text,sentiment_label,sentiment_score
0,5,For the record: listened to this one on audio....,2015-01-11,266,8,754,132,Alcatraz Versus the Evil Librarians,Brandon Sanderson,False,for the record listened to this one on audio ....,Positive,0.916096
1,3,Also known as The Official Author's Notes for ...,2016-09-07,175,39,5460,919,Alcatraz Versus the Evil Librarians,Brandon Sanderson,False,also known as the official author's notes for ...,Very Positive,0.309008
2,5,5 EYE-OPENING ST★RSHeads up! Goodreads librari...,2016-03-28,122,18,2444,407,Alcatraz Versus the Evil Librarians,Brandon Sanderson,False,5 eye-opening st rsheads up ! goodreads librar...,Very Negative,0.685168
3,2,Zaczynam się zastanawiać czy nie zaniżam ocen ...,2023-03-19,100,1,87,12,Alcatraz Versus the Evil Librarians,Brandon Sanderson,False,zaczynam się zastanawiać czy nie zaniżam ocen ...,Neutral,0.639101
4,4,Brandon Sanderson can write an instruction man...,2014-12-14,76,16,4219,710,Alcatraz Versus the Evil Librarians,Brandon Sanderson,False,brandon sanderson can write an instruction man...,Negative,0.540289

In [14]:
# Get the Average sentiment score and score per book
# Average score per book
avg_scores = df_clean.groupby("book_title")["sentiment_score"].mean().reset_index()
avg_scores.rename(columns={"sentiment_score": "avg_sentiment_score"}, inplace=True)

# Most common label per book
most_common_labels = (
    df_clean.groupby("book_title")["sentiment_label"]
    .agg(lambda x: x.value_counts().idxmax())
    .reset_index()
)
most_common_labels.rename(columns={"sentiment_label": "most_common_label"}, inplace=True)

# Combine both metrics
book_sentiment_summary = avg_scores.merge(most_common_labels, on="book_title")

book_sentiment_summary.head()

                            book_title  avg_sentiment_score most_common_label
0  Alcatraz Versus the Evil Librarians             0.686066          Positive

In [15]:
## Twitter Roberta Sentiment Analysis
#Load necessary libraries
from transformers import AutoModelForSequenceClassification
from transformers import TFAutoModelForSequenceClassification
from transformers import AutoTokenizer, AutoConfig
import numpy as np
from scipy.special import softmax


# Load the model
MODEL = "cardiffnlp/twitter-roberta-base-sentiment-latest"
tokenizer = AutoTokenizer.from_pretrained(MODEL)
model = AutoModelForSequenceClassification.from_pretrained(MODEL)
config = AutoConfig.from_pretrained(MODEL)


# Example usage
text = "Covid cases are increasing fast!"

# Encode the text
encoded_input = tokenizer(text, return_tensors='pt')  # PyTorch

# Run the model
output = model(**encoded_input)

# Apply Softmax to get probabilities
scores = softmax(output[0][0].detach().numpy())

# Rank Labels
ranking = np.argsort(scores)[::-1]  # from highest to lowest probability
for i in range(scores.shape[0]):
    l = config.id2label[ranking[i]]
    s = scores[ranking[i]]
    print(f"{i+1}) {l} {np.round(float(s), 4)}")

Some weights of the model checkpoint at cardiffnlp/twitter-roberta-base-sentiment-latest were not used when initializing RobertaForSequenceClassification: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

1) negative 0.7236
2) neutral 0.2287
3) positive 0.0477

In [16]:
# Function to perform sentiment analysis on long texts
def twitter_roberta_sentiment_analysis(text, chunk_size=512):
    # No preprocessing needed for Goodreads reviews
    # text = preprocess(text)  

    # Tokenize into wordpieces
    tokens = tokenizer.tokenize(text)
    chunks = [tokens[i:i + chunk_size] for i in range(0, len(tokens), chunk_size)]
    
    all_scores = []

    for chunk in chunks:
        chunk_text = tokenizer.convert_tokens_to_string(chunk)
        encoded_input = tokenizer(chunk_text, return_tensors='pt', truncation=True, max_length=chunk_size)
        output = model(**encoded_input)
        scores = softmax(output[0][0].detach().numpy())
        all_scores.append(scores)

    avg_scores = np.mean(all_scores, axis=0)
    final_label = config.id2label[np.argmax(avg_scores)]
    final_score = np.max(avg_scores)
    
    return final_label, final_score

In [17]:
# Process sentiment analysis on cleaned reviews
df_clean[["sentiment_label_tR", "sentiment_score_tR"]] = df_clean["cleaned_review_text"].apply(
    lambda x: pd.Series(twitter_roberta_sentiment_analysis(x))
)

In [18]:
# Get the Average sentiment score and score per book
# Average score per book
avg_scores = df_clean.groupby("book_title")["sentiment_score_tR"].mean().reset_index()
avg_scores.rename(columns={"sentiment_score_tR": "avg_sentiment_score_tR"}, inplace=True)

# Most common label per book
most_common_labels = (
    df_clean.groupby("book_title")["sentiment_label_tR"]
    .agg(lambda x: x.value_counts().idxmax())
    .reset_index()
)
most_common_labels.rename(columns={"sentiment_label_tR": "most_common_label_tR"}, inplace=True)

# Combine both metrics
book_sentiment_summary_2 = avg_scores.merge(most_common_labels, on="book_title")

book_sentiment_summary_2.head()

,book_title,avg_sentiment_score_tR,most_common_label_tR
0,Alcatraz Versus the Evil Librarians,0.802675,positive

In [21]:
df_details = pd.read_csv(r'C:\Programming\Python\msba_capstone_dragonsteel\Goodreads Data\Alcatraz_vs_Evil_Librarians.csv')
df_details.rename(columns={"Title": "book_title"}, inplace=True)
df_details.head()

,Author,book_title,Published Date,Audience Genre,Description,Average Rating,Total Ratings,Total Reviews,Non-Audience Genres,Currently Reading,Want to Read,URL
0,Brandon Sanderson,Alcatraz Versus the Evil Librarians,"October 1, 2007","Young Adult, Middle Grade, Childrens",Alcatraz Versus the Evil Librariansis the firs...,3.92,35429,5172,"Fantasy, Fiction, Audiobook, Humor",1799,30572,https://www.goodreads.com/book/show/623976.Alc...

In [22]:
df_details = df_details.merge(
    book_sentiment_summary,
    on="book_title",
    how="left"
)
df_details.head()

,Author,book_title,Published Date,Audience Genre,Description,Average Rating,Total Ratings,Total Reviews,Non-Audience Genres,Currently Reading,Want to Read,URL,avg_sentiment_score,most_common_label
0,Brandon Sanderson,Alcatraz Versus the Evil Librarians,"October 1, 2007","Young Adult, Middle Grade, Childrens",Alcatraz Versus the Evil Librariansis the firs...,3.92,35429,5172,"Fantasy, Fiction, Audiobook, Humor",1799,30572,https://www.goodreads.com/book/show/623976.Alc...,0.686066,Positive

In [23]:
df_details = df_details.merge(
    book_sentiment_summary_2,
    on="book_title",
    how="left"
)
df_details.head()

,Author,book_title,Published Date,Audience Genre,Description,Average Rating,Total Ratings,Total Reviews,Non-Audience Genres,Currently Reading,Want to Read,URL,avg_sentiment_score,most_common_label,avg_sentiment_score_tR,most_common_label_tR
0,Brandon Sanderson,Alcatraz Versus the Evil Librarians,"October 1, 2007","Young Adult, Middle Grade, Childrens",Alcatraz Versus the Evil Librariansis the firs...,3.92,35429,5172,"Fantasy, Fiction, Audiobook, Humor",1799,30572,https://www.goodreads.com/book/show/623976.Alc...,0.686066,Positive,0.802675,positive

In [24]:
df_details.to_csv(r'C:\Programming\Python\msba_capstone_dragonsteel\Goodreads Data\AvEL_details_with_sentiment.csv', index=False)